language: node_js
node_js: node
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: 6976......2353
    secure: VClaoprwssKV8eqtINh/a29KV94kbxdyDvndEVsOC8p9eREn73RsMQzN70d9fBA2MJh8UZrVCCOBYsMzONDUGH2LruBGHgwtqTPWH7/NQ00gfjWc1leyCcabhsITt1Vk4/D7Heifs9EVifIGBXfZOahfubCetTUjhU/OLPMGGkkZUdz+oDymoVa+C287a0CGDROKAiWjvf3EzR68hT++CP1KoY+2wEY0ZQ7curSoN6o/AmzDfMR1L7bRZ0USIit/ByzKmzcFoJzec5FM7iYgmqVbauwqGTc+PMubfeKeKeZSym6y8tduygnFB+b1RRbl9KJIs39ayvrzAx3v2SVzpCKhgle9OV96fPW4k8FV8YA7o35PiqU6uiy/6L0FnsSGllXkyyDTR1yGwfSDClicKd58a008QlzqkjnEx712FC1OB0F5ptG9Hndj7FzpAHqVP+YTqfEj+8CDmKvTHPSEZwguqCd3AcDQqpSDodWzPuXHFbEd59FECOUaRwz+rfFjDsP5oYea2xFtqpkePUf11GNuwL5KyBPCuXqnQZydUbIa/ssHluW870qH/ZavYi0FXtPXxtjgVRJFYg1iGyiir+JKw2ccSyUhPiokP91v6A8431KGi+PrNDNpJG69Tw7GF+CvESnpCEEUvk4gQPIIy/V6kVQU1UiNkoCphcMSNHI=
  on:
    tags: true
    repo: Brightspace/generator-polymer-init-d2l-polymer-2-element
